title: Kevin Giroux
description: Android Tips Blog
author: Kevin Giroux
logo: https://avatars3.githubusercontent.com/u/7769882?v=3&s=460
github: https://github.com/kgioux
about: IT Engineer
google_analytics: UA-72862926-1
urls:
    - text: Mes Articles
      url: /
      icon: fa-home
      layout: post
    - text: A propos de moi
      url: /about/
      icon: fa-comments
    - text: Mes projets
      url: /projects/
      icon: fa-desktop
    - text: CV
      url: /resume/
      icon: fa-graduation-cap
    - text: Language de Programmation
      url: /skillit/
      icon: fa-code
    - text: Outils
      url: /tools/
      icon: fa-wrench
    - text: Github
      url: https://github.com/kgiroux
      icon: fab fa-github

social:
    - icon: fab fa-facebook
      link: 'https://www.facebook.com/kevin.giroux.756'
    - icon: fab fa-twitter
      link: 'https://twitter.com/GirouxKevin'
    - icon: fab fa-linkedin
      link: 'https://www.linkedin.com/in/kevin-giroux-942809b3?trk=nav_responsive_tab_profile_pic'
    - icon: fab fa-stack-exchange
      link: 'http://stackoverflow.com/users/3211915/kevingiroux'
    - icon: fab fa-google-plus
      link: 'https://plus.google.com/109156652403283664005'

share:
  twitter_username: \GirouxKevin
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: ""
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
